[colors.primary]
background = '#141415'
foreground = '#cdcdcd'

# Normal colors
[colors.normal]
black   = '#606079'
red     = '#df6882'
green   = '#8cb66d'
yellow  = '#f3be7c'
blue    = '#7e98e8'
magenta = '#da87c1'
cyan    = '#6e94b2'
white   = '#9bb4bc'

# Bright colors
[colors.bright]
black   = '#adadbe'
red     = '#efb3c0'
green   = '#c5dab6'
yellow  = '#f9debe'
blue    = '#becbf3'
magenta = '#ecc3e0'
cyan    = '#b6c9d8'
white   = '#cdd9dd'
