[general]
import = [
    "~/.config/alacritty/theme.toml"
]
live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 15.5

[font.normal]
family = "IosevkaNerdFont"
style = "Medium"

[cursor]
style = { shape = "underline", blinking = "Always"}
blink_interval = 500
